### ISSUE TITLE
Hover over of numbers on landing page refer to report date rather than specimen/death date

### ISSUE THREAD

**Issue by DaveJephson** [publichealthengland/coronavirus-dashboard-summary#5]
'Last 7 days' numbers for cases and deaths have been switched to specimen/death date data. The hover text for these numbers needs updating to reflect this.

Correct by removing 'reported' from the hover over text.

Further issue is that the vaccination hover overs refer to a single day, not 'in the last 7 days'.

**Comment by beawitcht** [comment]
removed reported from hover text
@xenatisch would you be able to change the vaccination 7 day hovers to: "reported in the last 7 days (x - x)" please?
